#!/bin/bash

echo "🚀 Déploiement de BeatSync PRO sur Render (Alternative gratuite)"
echo ""

echo "📋 Instructions pour Render :"
echo ""
echo "1. Va sur https://render.com"
echo "2. Crée un compte gratuit"
echo "3. Connecte ton GitHub"
echo "4. Crée un 'Web Service' avec ces paramètres :"
echo ""
echo "   - Runtime: Docker"
echo "   - Build Command: (laisser vide)"
echo "   - Start Command: npm start"
echo ""
echo "5. Dans 'Advanced' :"
echo "   - Health Check Path: /"
echo "   - Environment: NODE_ENV=production"
echo ""
echo "🎁 Avantages de Render :"
echo "   ✅ 750 heures gratuites/mois"
echo "   ✅ Python + Node.js supportés"
echo "   ✅ Déploiement automatique depuis Git"
echo "   ✅ HTTPS automatique"
echo "   ✅ Support Docker"
echo ""

echo "💡 Après déploiement, ton app sera accessible 24/7 gratuitement !"